name: re_dash_inspector
description: A Flutter DevTools extension for re-dash
version: 0.1.0

repository: https://github.com/htihospitality/re-dash-inspector

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  devtools_extensions: ^0.3.0
  devtools_app_shared: ^0.3.0
  web: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - worker.js
