name: re_dash_inspector_worker
description: A Web Worker for the Flutter DevTools extension for re-dash
version: 0.1.0

repository: https://github.com/htihospitality/re-dash-inspector

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  web: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
